import { Contributor } from "./Contributor";
import { HistoryUpdateResearchTopic } from "./HistoryUpdateResearchTopic";
import { Author_ResearchTopics } from "./ResearchProjectTopic";
import { ReviewCouncilWithMembers } from "./ReviewCouncilWithMembers";

export type ResearchTopicWithContributors = {
  id: number;
  nameTopic: string;
  dateUpLoad: string;
  description: string;
  target: string;
  achievedResults?: string;
  summary?: string;
  budget: number;
  projectDuration: number;
  acceptanceApprovedStatus: number;
  reviewAcceptanceStatus: number;
  budgetFilePath: string;
  productFilePath: string;
  reportFilePath: string;
  dateStart: string;
  dateEnd: string;
  articleId: number;
  articleName: string;
  disciplineId: number;
  disciplineName: string;
  competitionId: number;
  review_CommitteeId?: number;
  reviewCommitteeName?: string;
  competitionName: string;
  supervisor: string;
  // coAuthors: Contributor[];
  review_Committees: ReviewCouncilWithMembers;
  history_Update_ResearchTopics: HistoryUpdateResearchTopic[];
  author_ResearchTopics: Author_ResearchTopics[];
  acceptance?: null | any;
};
