import { Contributor } from "./Contributor";
import { HistoryUpdateResearchTopic } from "./HistoryUpdateResearchTopic";
import { ReviewCouncilWithMembers } from "./ReviewCouncilWithMembers";

export type ResearchProjectTopic = {
  id: number;
  nameTopic: string;
  dateUpLoad: string | Date;
  description: string;
  target: string;
  achievedResults: string;
  budget: number;
  projectDuration: number;
  acceptanceApprovedStatus: number;
  reviewAcceptanceStatus: number;
  budgetFilePath: string;
  productFilePath: string;
  reportFilePath: string;
  dateStart: string;
  dateEnd: string;
  articleId: number;
  articleName: string;
  disciplineId: number;
  disciplineName: string;
  competitionId: number;
  review_CommitteeId?: number;
  competitionName: string;
  supervisor: string;
  //coAuthors: Contributor[];
  review_Committees: ReviewCouncilWithMembers;
  history_Update_ResearchTopics: HistoryUpdateResearchTopic[];
  author_ResearchTopics: Author_ResearchTopics[];
};
export type Author_ResearchTopics = {
  researchTopicId: number;
  authorId: number;
  roleName: string;
  author: {
    id: number;
    name: string;
    dateOfBirth: string;
    sex: string;
    numberPhone: string;
    facultyId: number;
    facultyName: string;
    internalCode: string;
    accountId: number;
    email: string;
  };
  deletedAt: any;
};
